server:
  port: 8080

#logging:
#  file:
#    name: log\log.log

spring:
  sql:
    init:
      continue-on-error: true
  datasource:
    sqlite:
      jdbc-url: jdbc:sqlite:db.db
      driver-class-name: org.sqlite.JDBC
      username:
      password:
  # 关闭 Redisson 自动配置，手工创建 RedissonClient
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

app:
  name: backend-example-java
  env: dev

  #  lock-service: redisson   # reentrant[default] | redisson
  #  lock-redisson-address: redis://localhost:6379
  #  lock-redisson-password:
  #  lock-redisson-database: 0

  jwt-expires: 30d
  jwt-secret: jwt-secret-string
